<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
<meta http-equiv="Content-Language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<meta name="author" content="" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<link href="/admin/templates/start.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="wrap">
	<div id="cont">

		<div id="edit"></div>
		<div id="cms"></div>
		<div id="login">
			<form method="post" action="">
			<table>
				<tr><td class="text">Login</td><td><input type="text" name="login[login]" /></td></tr>
				<tr><td class="text">Password</td><td><input type="password" name="login[password]" /></td></tr>
				<tr><td></td><td><input type="hidden" name="auth" value="1" /><input type="submit" value="Login" class="btn_type_1" /></td></tr>

			</table>
			</form>
		</div>
	</div>
</div>

</body>
</html>