<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="ru" />
<meta name="description" content="<?= isset($description)?$description:''?>" />
<title><?= isset($title)?$title:''?></title>
<meta name="keywords" content="<?= isset($keywords)?$keywords:''?>" />
<link href="/component/index/css/style.css" rel="stylesheet" type="text/css" />
<script src="http://code.jquery.com/jquery-latest.min.js"></script>


<!-- Add mousewheel plugin (this is optional) -->
<script type="text/javascript" src="<?=Config::SITE_URL?>component/main/js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
<script type="text/javascript" src="<?=Config::SITE_URL?>component/index/js/scripts.js"></script>

<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="<?=Config::SITE_URL?>component/main/js/fancybox/source/jquery.fancybox.js?v=2.1.5"></script>
<link rel="stylesheet" type="text/css" href="/component/main/js/fancybox/source/jquery.fancybox.css?v=2.1.5" media="screen" />

<!-- Add Button helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="/component/main/js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />