<?php if(isset($search_param)){?>
    <form name="search" action="" method="post">
        <table width="100%"  border="1" cellpadding="0" cellspacing="0" align="right"  >
         <tbody>
             <tr align="right">
            <?php            foreach ($search_param as $search){?>
            <td><?= admin_view_search::$search['name_function']($search)?></td>
                <?php }?>
        </tr>
    </tbody>
</table>
        <input type="submit" value="искать">
    </form>
<?php } ?>
