<div class="wrapper">
    <a href="index.html" title="" class="logo"><img src="images/logo.png" alt="" /></a>    

    <!-- Right top nav -->
    <div class="topNav">
        <ul class="userNav">
            <li><a title="" class="search"></a></li>

            <li><a href="<?=  app::I()->MakeUrl('admin_user', 'logaut',array('admin'=>''))?>" title="Выйти" class="logout"></a></li>
            <li class="showTabletP"><a href="#" title="" class="sidebar"></a></li>
        </ul>
        <a title="" class="iButton"></a>
        <a title="" class="iTop"></a>
        <div class="topSearch">
            <div class="topDropArrow"></div>
            <form action="">
                <input type="text" placeholder="search..." name="topSearch" />
                <input type="submit" value="" />
            </form>
        </div>
    </div>

    <!-- Responsive nav -->

    <div class="clear"></div>
</div>