<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?= isset($title) ? $title : '' ?></title>

<link rel="stylesheet" href="/component/main/css/960.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="/component/main/css/template.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="/component/main/css/colour.css" type="text/css" media="screen" charset="utf-8" />

<!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />-->

<!--[if lte IE 7]>
<style type="text/css">
html .jqueryslidemenu{height: 1%;} /*Holly Hack for IE7 and below*/
</style>
<![endif]-->


<script language="javascript" type="text/javascript" src="/component/main/js/tiny_mce/tinymce.min.js"></script>

<link rel="stylesheet" type="text/css" href="/component/main/js/jqueryslidemenu.css">
<script type="text/javascript" src="/component/main/js/jqueryslidemenu.js"></script>
<script type="text/javascript" src="/component/main/js/for_admin.js"></script>
<script type="text/javascript" src="/component/main/js/jquery.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		// General options
		mode: "textareas",
		theme: "modern",
		plugins: ["moxiemanager advlist autolink lists link image charmap print preview hr anchor pagebreak",
			"searchreplace wordcount visualblocks visualchars code fullscreen",
			"insertdatetime media nonbreaking save table contextmenu directionality ",
			"emoticons template paste textcolor"]
		,
		editor_selector: "UserEditor",
		// Theme options
		toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
		toolbar2: "print preview media | forecolor backcolor emoticons",
		extended_valid_elements: "script[language|type|src]",
		image_advtab: true,
		remove_script_host: false,
		convert_urls: false,
		theme_advanced_resizing: true,
		// Example content CSS (should be your site CSS)



		// Replace values for the template plugin
		template_replace_values: {
			username: "Some User",
			staffid: "991234"
		}
	});
</script>



<? /*
  <script type="text/javascript" src="/highslide/highslide-with-gallery.js"></script>
  <link rel="stylesheet" type="text/css" href="/highslide/highslide.css" />
 */ ?>
<!--
	2) Optionally override the settings defined at the top
	of the highslide.js file. The parameter hs.graphicsDir is important!
-->

<!-- Add mousewheel plugin (this is optional) -->
<script type="text/javascript" src="/component/main/js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="/component/main/js/fancybox/source/jquery.fancybox.js?v=2.1.5"></script>
<link rel="stylesheet" type="text/css" href="/component/main/js/fancybox/source/jquery.fancybox.css?v=2.1.5" media="screen" />

<!-- Add Button helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="/component/main/js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
<script type="text/javascript" src="/component/main/js/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

