<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#fbffc3">
    <tbody>
        <tr>

            <td  width="75"bgcolor="#8f4e09"  > </td>
            <td >




                <?php
                $picture = array('name' => 'Воспоминание" х\м;', 'size' => '95х82', 'height' => 168, 'path' => 'images/portret/Vospominanie.gif');
                $pictures = array($picture, $picture, $picture, $picture, $picture, $picture, $picture, $picture);
                echo view::template('view/views/view_picture_2_line.phtml',array('pictures'=>$pictures)); ?>
            </td>
        </tr>
    </tbody>
</table> 