
<div class="secTop">
    <div class="balance">
        <div class="balInfo">

        </div>
    </div>

</div>

<!-- Tabs container -->
<div id="tab-container" class="tab-container">
    <ul class="iconsLine ic2 etabs">
        <li class="clicked">
            <a title="Пользователи" href="<?= app::I()->MakeUrl('admin_user', '', array('admin' => '')) ?>" class="clicked">
                <span class="icos-user"></span>
            </a>
        </li>
        <li class="">
            <a title="Группы пользователей" href="<?= app::I()->MakeUrl('admin_user', 'groups', array('admin' => '')) ?>" class="">
                <span class="icos-users"></span>
            </a>
        </li>
    </ul>


    <div class="divider"><span></span></div>

    <div id="general">
        <ul class="subNav">
            <li><a href="ui.html" title="" class="this"><span class="icos-fullscreen"></span>General elements</a></li>
            <li><a href="ui_icons.html" title=""><span class="icos-images2"></span>Icons</a></li>
            <li><a href="ui_buttons.html" title=""><span class="icos-coverflow"></span>Button sets</a></li>
            <li><a href="ui_grid.html" title=""><span class="icos-view"></span>Grid</a></li>
            <li><a href="ui_custom.html" title=""><span class="icos-cog2"></span>Custom elements</a></li>
            <li><a href="ui_experimental.html" title=""><span class="icos-beta"></span>Experimental</a></li>
        </ul>
    </div>


</div>

<div class="divider"><span></span></div>

